spring:
  datasource:
    url: jdbc:mysql://localhost:3306/onl_jee_w_20?serverTimezone=UTC
    username: root
    password: coderslab
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  web:
    locale: pl_PL
    locale-resolver: fixed